list_deps = [
    "scikit-image",
    "pandas",
    "affine",
    "rasterio",
    "xsdata",
    "attrs",
    "toml",
    "lxml",
    "pytest",
    "branca",
    "cachetools",
    "netCDF4",
    "certifi",
    "brotli",
    "babel",
    "beautifulsoup4",
    "binaryornot",
    "bitmath",
    "decorator",
    "debugpy",
    "backcall",
    "bleach",
    "boltons",
    "blosc",
    "blessings",
    "pystac-client",
    "setuptools",
    "planetary-computer",
    "cycler",
    "pystac",
    "defusedxml",
    "scipy",
    "coverage",
    "click-default-group",
    "colorlog",
    "colorama",
    "colour",
    "cligj",
    "click-plugins",
    "asttokens",
    "charset-normalizer",
    "click",
    "async-lru",
    "build",
    "bump2version",
    "cookiecutter",
    "chardet",
    "contourpy",
    "comm",
    "arrow",
    "cftime",
    "appdirs",
    "argcomplete",
    "argon2-cffi",
    "cffi",
    "nox",
    "argon2-cffi-bindings",
    "docutils",
    "geopandas",
    "fiona",
    "future",
    "filelock",
    "fqdn",
    "fonttools",
    "tifftools",
    "rioxarray",
    "ruff",
    "ratelim",
    "tenacity",
    "untokenize",
    "scooby",
    "plotly",
    "toposort",
    "uritemplate",
    "traittypes",
    "widgetsnbextension",
    "pyasn1",
    "pywavelets",
    "zfp",
    "h5py",
    "imageio",
    "pyproject-api",
    "anyio",
    "google-crc32c",
    "grayskull",
    "odc-stac",
    "odc-geo",
    "httplib2",
    "geographiclib",
    "fmt",
    "exceptiongroup",
    "executing",
    "docformatter",
    "distro",
    "elementpath",
    "tox",
    "alabaster",
    "jupyterlab_widgets",
    "appdirs",
    "distlib",
    "earthengine-api",
    "flake8",
    "pycodestyle",
    "sphinx",
    "python-dotenv",
    "dill",
    "tree",
    "xarray",
    "folium",
    "nbsphinx",
    "jupyterlab",
    "make",
    "geopy",
    "xmltodict",
    "pip"
]

list_conda_install = [
    "'conda-build<24'",
    "numba==0.57.0",
    "boa"
]

# list_subPackages = [
#     "btklogger",
#     "btkdatamgmt",
#     "btkdatamgmtascii",
#     "btkdatamgmtaux",
#     "btkdatamgmtbrk",
#     "btkdatamgmtdgm",
#     "btkqualitytools",
#     "btkprocessor",
#     "btkprocessorl1",
#     "btkprocessorl1framing",
#     "btkprocessorstack",
#     "btkprocessorl2",
#     "btkdevkit",
# ]

list_subPackages = [
    "btklogger-2.3.2-py_0.tar.bz2",
    "btkdatamgmt-2.3.2-py_0.tar.bz2",
    "btkdatamgmtascii-2.3.2-py_0.tar.bz2",
    "btkdatamgmtaux-2.3.2-py_0.tar.bz2",
    "btkdatamgmtbrk-2.3.2-py_0.tar.bz2",
    "btkdatamgmtdgm-2.3.2-py_0.tar.bz2",
    "btkqualitytools-2.3.2-py_0.tar.bz2",
    "btkprocessor-2.3.2-py_0.tar.bz2",
    "btkprocessorl1-2.3.2-py_0.tar.bz2",
    "btkprocessorl1framing-2.3.2-py_0.tar.bz2",
    "btkprocessorstack-2.3.2-py_0.tar.bz2",
    "btkprocessorl2-2.3.2-py_0.tar.bz2",
    "btkdevkit-2.3.2-py_0.tar.bz2",
]

list_bps_packages = [
   "arepyextras-runner-1.0.2-py_0.tar.bz2",
   "bps-l1_framing_processor-2.2.0-py_0.tar.bz2",
   "bps-l2b_fd_processor-2.2.0-py_0.tar.bz2",
   "bps-stack_pre_processor-2.2.0-py_0.tar.bz2",
   "arepytools-1.6.1-py_0.tar.bz2",
   "bps-l1_pre_processor-2.2.0-py_0.tar.bz2",
   "bps-l2b_fh_processor-2.2.0-py_0.tar.bz2",
   "bps-stack_processor-2.2.0-py_0.tar.bz2",
   "bps-common-2.2.0-py_0.tar.bz2",
   "bps-l1_processor-2.2.0-py_0.tar.bz2",
   "bps-stack_cal_processor-2.2.0-py_0.tar.bz2",
   "bps-transcoder-2.2.0-py_0.tar.bz2",
   "bps-l1_core_processor-2.2.0-py_0.tar.bz2",
   "bps-l2a_processor-2.2.0-py_0.tar.bz2",
   "bps-stack_coreg_processor-2.2.0-py_0.tar.bz2",
#    "arepyextras-quality-1.1.1-py_0.tar.bz2",
#    "arepyextras-copernicus_dem_extractor-3.1.3-py_0.tar.bz2"
]

